//
// auto-generated by op2.py
//

//user function
#include ".././src/Kernels/copy_double_kernel.h"
//user function
//#pragma acc routine
inline void copy_double_kernel_openacc( 
	const double* variables,
	double* old_variables) {
	for (int i=0; i<NVAR; i++) {
		old_variables[i] = variables[i];
	}
}

// host stub function
void op_par_loop_copy_double_kernel(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1){

  int nargs = 2;
  op_arg args[2];
  const int nk = 5;

  args[0] = arg0;
  args[1] = arg1;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(nk);
  op_timers_core(&cpu_t1, &wall_t1);
  OP_kernels[nk].name      = name;
  OP_kernels[nk].count    += 1;


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  copy_double_kernel");
  }

  op_mpi_halo_exchanges_cuda(set, nargs, args);


  if (set->size >0) {


    //Set up typed device pointers for OpenACC

    double* data0 = (double*)arg0.data_d;
    double* data1 = (double*)arg1.data_d;
    #pragma acc parallel loop independent deviceptr(data0,data1)
    for ( int n=0; n<set->size; n++ ){
      copy_double_kernel_openacc(
        &data0[5*n],
        &data1[5*n]);
    }
  }

  // combine reduction data
  op_mpi_set_dirtybit_cuda(nargs, args);

  // update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[nk].time     += wall_t2 - wall_t1;
  OP_kernels[nk].transfer += (float)set->size * arg0.size;
  OP_kernels[nk].transfer += (float)set->size * arg1.size * 2.0f;
}
