//
// auto-generated by op2.py
//

//user function
#include ".././src/Kernels/mg.h"

// host stub function
void op_par_loop_up_kernel(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1,
  op_arg arg2){

  int nargs = 3;
  op_arg args[3];
  const int nk = 16;

  args[0] = arg0;
  args[1] = arg1;
  args[2] = arg2;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(nk);
  op_timers_core(&cpu_t1, &wall_t1);

  if (OP_diags>2) {
    printf(" kernel routine with indirection: up_kernel\n");
  }

  int set_size = op_mpi_halo_exchanges(set, nargs, args);

  if (set->size >0) {

    for ( int n=0; n<set->core_size; n++ ){
      int map1idx = arg1.map_data[n * arg1.map->dim + 0];

      up_kernel(
        &((double*)arg0.data)[5 * n],
        &((double*)arg1.data)[5 * map1idx],
        &((int*)arg2.data)[1 * map1idx]);
    }

    if (set_size > set->core_size) {
      op_mpi_wait_all(nargs, args);
      for ( int n=set->core_size; n<set_size; n++ ){
        int map1idx = arg1.map_data[n * arg1.map->dim + 0];

        up_kernel(
          &((double*)arg0.data)[5 * n],
          &((double*)arg1.data)[5 * map1idx],
          &((int*)arg2.data)[1 * map1idx]);
      }
    }
  }

  if (set_size == 0 || set_size == set->core_size) {
    op_mpi_wait_all(nargs, args);
  }
  // combine reduction data
  op_mpi_set_dirtybit(nargs, args);

  // update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[nk].name      = name;
  OP_kernels[nk].count    += 1;
  OP_kernels[nk].time     += wall_t2 - wall_t1;
  OP_kernels[nk].transfer += (float)set->size * arg1.size * 2.0f;
  OP_kernels[nk].transfer += (float)set->size * arg2.size * 2.0f;
  OP_kernels[nk].transfer += (float)set->size * arg0.size;
  OP_kernels[nk].transfer += (float)set->size * arg1.map->dim * 4.0f;
}
