//
// auto-generated by op2.py
//

#include <math.h>
#include "const.h"

//user function
class down_v2_kernel_pre_kernel;

//host stub function
void op_par_loop_down_v2_kernel_pre(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1){

  int nargs = 2;
  op_arg args[2];

  args[0] = arg0;
  args[1] = arg1;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(19);
  op_timers_core(&cpu_t1, &wall_t1);
  OP_kernels[19].name      = name;
  OP_kernels[19].count    += 1;


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  down_v2_kernel_pre\n");
  }

  int exec_size = op_mpi_halo_exchanges_cuda(set, nargs, args);
  if (exec_size > 0) {

    const int direct_down_v2_kernel_pre_stride_OP2CONSTANT = getSetSizeFromOpArg(&arg0);
    //set SYCL execution parameters
    #ifdef OP_BLOCK_SIZE_19
      int nthread = OP_BLOCK_SIZE_19;
    #else
      int nthread = OP_block_size;
    #endif

    int nblocks = 200;

    double *arg0_d = (double*)arg0.data_d;
    double *arg1_d = (double*)arg1.data_d;
    int set_size = set->size+set->exec_size;
    try {
    op2_queue->wait();
    op2_queue->submit([&](cl::sycl::handler& cgh) {

      //user fun as lambda
      auto down_v2_kernel_pre_gpu = [=]( 
            double* weight_sum,
            double* residual_sum) {
            weight_sum[(0)*direct_down_v2_kernel_pre_stride_OP2CONSTANT]= 0.0;
            residual_sum[VAR_DENSITY] = 0.0;
            residual_sum[VAR_MOMENTUM+0] = 0.0;
            residual_sum[VAR_MOMENTUM+2] = 0.0;
            residual_sum[VAR_MOMENTUM+1] = 0.0;
            residual_sum[VAR_DENSITY_ENERGY] = 0.0;
        
        };
        
      auto kern = [=](cl::sycl::item<1> item) [[intel::reqd_sub_group_size(SIMD_VEC)]] {

        //process set elements
        int n = item.get_id(0);
        if (n < exec_size) {

          //user-supplied kernel call
          down_v2_kernel_pre_gpu(&arg0_d[n],
                                 &arg1_d[n*1]);
        }

      };
      cgh.parallel_for<class down_v2_kernel_pre_kernel>(cl::sycl::range<1>(set_size), kern);
    });
    }catch(cl::sycl::exception const &e) {
    std::cout << e.what() << std::endl;exit(-1);
    }
  }
  op_mpi_set_dirtybit_cuda(nargs, args);
  op2_queue->wait();
  //update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[19].time     += wall_t2 - wall_t1;
  OP_kernels[19].transfer += (float)set->size * arg0.size * 2.0f;
  OP_kernels[19].transfer += (float)set->size * arg1.size * 2.0f;
}
