//
// auto-generated by op2.py
//

// Copyright 2009, Andrew Corrigan, acorriga@gmu.edu
// This code is from the AIAA-2009-4001 paper

// Warwick extensions:
// - multigrid, per-edge computation, n-neighbours
// - residual calculation, solution validation

//
// sparse tiling headers
//

#ifdef SLOPE
#include "executor.h"
#include "inspector.h"
#endif

#define TILE_SIZE 5000

#include <stdio.h>
#include <iostream>
#include <fstream>
#include <cmath>
#include <string>
#include <omp.h>
#include <sys/time.h>
#include <sstream>
#include <cstdlib>
#include <map>
#include <vector>
#include <limits>

#include "hdf5.h"

#ifdef PAPI
#include "papi_funcs.h"
#endif

// #define LOG_PROGRESS

// OP2:
#include  "op_lib_cpp.h"

#define double_ALIGN 128
#define float_ALIGN 64
#define int_ALIGN 64
#ifdef VECTORIZE
#define SIMD_VEC 4
#ifdef __clang__
  // Clang-compiled SIMD loop always performs 2 serial iterations,
  // so need to make the SIMD loop wider than 'SIMD_VEC'
  #define SIMD_BLOCK_SIZE ((SIMD_VEC*3)+2)
  // #define SIMD_BLOCK_SIZE ((SIMD_VEC*2)+2)
#else
  #define SIMD_BLOCK_SIZE SIMD_VEC
#endif
#define ALIGNED_double __attribute__((aligned(double_ALIGN)))
#define ALIGNED_float __attribute__((aligned(float_ALIGN)))
#define ALIGNED_int __attribute__((aligned(int_ALIGN)))
#ifdef __ICC
  #define DECLARE_PTR_ALIGNED(X, Y) __assume_aligned(X, Y)
#else
  #define DECLARE_PTR_ALIGNED(X, Y)
#endif
#include "compute_flux_edge_kernel_veckernel.h"
#else
#define ALIGNED_double
#define ALIGNED_float
#define ALIGNED_int
#define DECLARE_PTR_ALIGNED(X, Y)
#endif

//
// op_par_loop declarations
//
#ifdef OPENACC
#ifdef __cplusplus
extern "C" {
#endif
#endif

void op_par_loop_initialize_variables_kernel(char const *, op_set,
  op_arg );

void op_par_loop_zero_5d_array_kernel(char const *, op_set,
  op_arg );

void op_par_loop_zero_1d_array_kernel(char const *, op_set,
  op_arg );

void op_par_loop_calculate_cell_volumes(char const *, op_set,
  op_arg,
  op_arg,
  op_arg,
  op_arg,
  op_arg );

void op_par_loop_dampen_ewt(char const *, op_set,
  op_arg );

void op_par_loop_copy_double_kernel(char const *, op_set,
  op_arg,
  op_arg );

void op_par_loop_calculate_dt_kernel(char const *, op_set,
  op_arg,
  op_arg,
  op_arg );

void op_par_loop_get_min_dt_kernel(char const *, op_set,
  op_arg,
  op_arg );

void op_par_loop_compute_step_factor_kernel(char const *, op_set,
  op_arg,
  op_arg,
  op_arg,
  op_arg );

void op_par_loop_compute_flux_edge_kernel(char const *, op_set,
  op_arg,
  op_arg,
  op_arg,
  op_arg,
  op_arg );

void op_par_loop_compute_flux_edge_kernel_instrumented(char const *, op_set,
  op_arg,
  op_arg,
  op_arg,
  op_arg,
  op_arg
  #ifdef VERIFY_OP2_TIMING
    , double* // compute time
    , double* // sync time
  #endif
  , long* // iterations
  #ifdef PAPI
    , long_long*, int, int
  #endif
);

void op_par_loop_compute_bnd_node_flux_kernel(char const *, op_set,
  op_arg,
  op_arg,
  op_arg,
  op_arg );

void op_par_loop_time_step_kernel(char const *, op_set,
  op_arg,
  op_arg,
  op_arg,
  op_arg,
  op_arg );

void op_par_loop_indirect_rw_kernel(char const *, op_set,
  op_arg,
  op_arg,
  op_arg,
  op_arg,
  op_arg );

void op_par_loop_residual_kernel(char const *, op_set,
  op_arg,
  op_arg,
  op_arg );

void op_par_loop_calc_rms_kernel(char const *, op_set,
  op_arg,
  op_arg );

void op_par_loop_count_bad_vals(char const *, op_set,
  op_arg,
  op_arg );

void op_par_loop_up_pre_kernel(char const *, op_set,
  op_arg,
  op_arg );

void op_par_loop_up_kernel(char const *, op_set,
  op_arg,
  op_arg,
  op_arg );

void op_par_loop_up_post_kernel(char const *, op_set,
  op_arg,
  op_arg );

void op_par_loop_down_v2_kernel_pre(char const *, op_set,
  op_arg,
  op_arg );

void op_par_loop_down_v2_kernel(char const *, op_set,
  op_arg,
  op_arg,
  op_arg,
  op_arg,
  op_arg,
  op_arg,
  op_arg,
  op_arg,
  op_arg,
  op_arg );

void op_par_loop_down_v2_kernel_post(char const *, op_set,
  op_arg,
  op_arg,
  op_arg,
  op_arg );

void op_par_loop_down_kernel(char const *, op_set,
  op_arg,
  op_arg,
  op_arg,
  op_arg,
  op_arg );

void op_par_loop_identify_differences(char const *, op_set,
  op_arg,
  op_arg,
  op_arg );

void op_par_loop_count_non_zeros(char const *, op_set,
  op_arg,
  op_arg );
#ifdef OPENACC
#ifdef __cplusplus
}
#endif
#endif

#include "op_hdf5.h"

// MG-CFD base:
#include "const.h"
#include "structures.h"
#include "inlined_funcs.h"
#include "config.h"
#include "utils.h"
#include "io.h"
#include "timer.h"

// Global scalars:
double smoothing_coefficient = double(0.2f);
double ff_variable[NVAR];
double ff_flux_contribution_momentum_x[NDIM];
double ff_flux_contribution_momentum_y[NDIM];
double ff_flux_contribution_momentum_z[NDIM];
double ff_flux_contribution_density_energy[NDIM];
int mesh_name;
#include "global.h"
#ifdef PAPI
int num_events;
#endif
config conf;

// MG-CFD kernels:
#include "flux.h"
#include "mg.h"
#include "time_stepping_kernels.h"
#include "compute_node_area_kernel.h"
#include "validation.h"
#include "indirect_rw.h"
#include "misc.h"

int main(int argc, char** argv)
{
    #ifdef NANCHECK
        feenableexcept(FE_ALL_EXCEPT & ~FE_INEXACT);
    #endif
    
    set_config_defaults();
    if (!parse_arguments(argc, argv)) {
        return 1;
    }
    if (strcmp(conf.input_file, "") == 0) {
        op_printf("ERROR: input_file not set\n");
        return 1;
    }

    const char* input_file_name = conf.input_file;
    const char* input_directory = conf.input_file_directory;
    if (strcmp(input_directory, "")!=0) {
        input_file_name = strdup((std::string(input_directory) + "/" + input_file_name).c_str());
    }

    int problem_size = 0;
    int levels = 0;
    int base_array_index = 1;
    std::string* layers = NULL;
    std::string* mg_connectivity_filename = NULL;
    read_input_dat(input_file_name, &problem_size, &levels, &base_array_index, &layers, &mg_connectivity_filename);
    if (strcmp(input_directory, "")!=0) {
        for (int l=0; l<levels; l++) {
            layers[l] = (std::string(input_directory) + "/" + layers[l]).c_str();
            if (l < (levels-1))
                mg_connectivity_filename[l] = (std::string(input_directory) + "/" + mg_connectivity_filename[l]).c_str();
        }
    }

    if (base_array_index >= 1 && base_array_index <= 9) {
      // Append 'base_array_index' to args:

      char** new_argv = (char**)malloc((argc+1)*sizeof(char*));
      for (int i=0; i<argc; i++) {
        new_argv[i] = (char*)malloc((strlen(argv[i])+1)*sizeof(char));
        strcpy(new_argv[i], argv[i]);
      }
      new_argv[argc] = (char*)malloc((strlen("OP_MAPS_BASE_INDEX=0")+1)*sizeof(char));
      sprintf(new_argv[argc], "OP_MAPS_BASE_INDEX=%d", base_array_index);
      argc++;

      argv = new_argv;
    }

    #ifdef LOG_PROGRESS
        // op_init(argc, argv, 7); // Report positive checks in op_plan_check
        // op_init(argc, argv, 4);
        op_init(argc, argv, 3); // Report execution of parallel loops
        // op_init(argc, argv, 2); // Info on plan construction
        // op_init(argc, argv, 1); // Error-checking
    #else
        op_init(argc, argv, 0);
    #endif

    // timer
    double cpu_t1, cpu_t2, wall_t1, wall_t2;

    #ifdef VERIFY_OP2_TIMING
        double flux_kernel_compute_times[levels];
        for (int i=0; i<levels; i++) {
            flux_kernel_compute_times[i] = 0.0;
        }
        double flux_kernel_sync_times[levels];
        for (int i=0; i<levels; i++) {
            flux_kernel_sync_times[i] = 0.0;
        }
    #endif
    long flux_kernel_iter_counts[levels];
    for (int i=0; i<levels; i++) {
        flux_kernel_iter_counts[i] = 0;
    }
    #ifdef PAPI
        int num_events = 0;
        init_papi(&num_events);
        long_long flux_kernel_event_counts[levels*num_events];
        for (int i=0; i<(levels*num_events); i++) {
            flux_kernel_event_counts[i] = 0;
        }

        int event_set;
        int* events;
        load_papi_events(num_events, &event_set, &events);
    #endif

    // set far field conditions
    {
        const double angle_of_attack = double(PI / 180.0) * double(deg_angle_of_attack);

        ff_variable[VAR_DENSITY] = double(1.4);

        double ff_pressure = double(1.0);
        double ff_speed_of_sound = sqrt(GAMMA*ff_pressure / ff_variable[VAR_DENSITY]);
        double ff_speed = double(ff_mach)*ff_speed_of_sound;

        double3 ff_velocity;
        ff_velocity.x = ff_speed*double(cos((double)angle_of_attack));
        ff_velocity.y = ff_speed*double(sin((double)angle_of_attack));
        ff_velocity.z = 0.0;

        ff_variable[VAR_MOMENTUM+0] = ff_variable[VAR_DENSITY] * ff_velocity.x;
        ff_variable[VAR_MOMENTUM+1] = ff_variable[VAR_DENSITY] * ff_velocity.y;
        ff_variable[VAR_MOMENTUM+2] = ff_variable[VAR_DENSITY] * ff_velocity.z;

        ff_variable[VAR_DENSITY_ENERGY] = ff_variable[VAR_DENSITY]*(double(0.5)*(ff_speed*ff_speed))
                                        + (ff_pressure / double(GAMMA-1.0));

        double3 ff_momentum;
        ff_momentum.x = *(ff_variable+VAR_MOMENTUM+0);
        ff_momentum.y = *(ff_variable+VAR_MOMENTUM+1);
        ff_momentum.z = *(ff_variable+VAR_MOMENTUM+2);
        compute_flux_contribution(ff_variable[VAR_DENSITY], ff_momentum,
                                    ff_variable[VAR_DENSITY_ENERGY],
                                    ff_pressure, ff_velocity,
                                    ff_flux_contribution_momentum_x,
                                    ff_flux_contribution_momentum_y,
                                    ff_flux_contribution_momentum_z,
                                    ff_flux_contribution_density_energy);
    }

    #ifdef SLOPE
    int avg_tile_size = conf.tile_size; 
    double* coordinates;
    int nloops = 5;
    int seed_loop = 0;
    // sets
    set_t* sl_nodes[levels];
    set_t* sl_edges[levels]; 
    set_t* sl_bnd_nodes[levels];

    map_t* sl_edge_to_nodes[levels];
    map_t* sl_bnd_node_to_node[levels];

    desc_list compute_flux_desc[levels];
    desc_list compute_bflux_desc[levels];
    desc_list time_step_desc[levels];
    desc_list indirect_rw_desc[levels];
    desc_list zero_5d_array_desc[levels];

    map_list mesh_maps[levels];

    inspector_t* insp[levels];
    executor_t* exec[levels];
    std::string sl_maps_edge_to_nodes[levels];
    std::string sl_maps_bnd_node_to_node[levels];
    #endif

    // Set elements:
    op_set op_nodes[levels],
           op_edges[levels],
           op_bnd_nodes[levels];

    // Set mappings:
    op_map p_edge_to_nodes[levels],
           p_bnd_node_to_node[levels]
           ;

    // MG mapping:
    op_map* p_node_to_mg_node = NULL;
    op_map* p_edge_to_mg_nodes = NULL;
    if (levels > 1) {
        p_node_to_mg_node = alloc<op_map>(levels-1);
        p_edge_to_mg_nodes = alloc<op_map>(levels-1);
    }

    // Set data:
    op_dat p_edge_weights[levels],
           p_bnd_node_weights[levels],
           p_bnd_node_groups[levels],
           p_node_coords[levels];

    op_dat variables_correct[levels];

    // Temporary set data (ie, arrays that are populated by kernels)
    op_dat p_variables[levels], 
           p_old_variables[levels], 
           p_residuals[levels],
           p_residuals_prolonged[levels],
           p_residuals_prolonged_wsum[levels],
           p_volumes[levels],
           p_step_factors[levels],
           p_fluxes[levels];
    op_dat p_up_scratch[levels];

    // Setup OP2
    char* op_name = alloc<char>(100);
    #ifdef SLOPE
    char* sl_name = alloc<char>(100);
    #endif
    {
              op_decl_const2("smoothing_coefficient",1,"double",&smoothing_coefficient);
              op_decl_const2("ff_variable",5,"double",ff_variable);
              op_decl_const2("ff_flux_contribution_momentum_x",3,"double",ff_flux_contribution_momentum_x);
              op_decl_const2("ff_flux_contribution_momentum_y",3,"double",ff_flux_contribution_momentum_y);
              op_decl_const2("ff_flux_contribution_momentum_z",3,"double",ff_flux_contribution_momentum_z);
              op_decl_const2("ff_flux_contribution_density_energy",3,"double",ff_flux_contribution_density_energy);
              op_decl_const2("mesh_name",1,"int",&mesh_name);

        op_printf("-----------------------------------------------------\n");
        op_printf("Loading from HDF5 files ...\n");

        for (int i=0; i<levels; i++) {
            op_printf("Loading level %d / %d\n", i+1, levels);
            
            sprintf(op_name, "op_nodes_L%d", i);
            if (conf.legacy_mode) {
                op_nodes[i] = op_decl_set_hdf5_infer_size(layers[i].c_str(), op_name, "node_coordinates.renumbered");
            } else {
                op_nodes[i] = op_decl_set_hdf5_infer_size(layers[i].c_str(), op_name, "node_coordinates");
                #ifdef SLOPE
                sprintf(sl_name, "sl_nodes_L%d", i);
                sl_nodes[i] = set(sl_name, op_nodes[i]->size);
                #endif
            }

            if (conf.legacy_mode) {
                sprintf(op_name, "op_edges_L%d", i);
                op_edges[i] = op_decl_set_hdf5_infer_size(layers[i].c_str(), op_name, "edge-->node.renumbered");
            } else {
                sprintf(op_name, "op_edges_L%d", i);
                op_edges[i] = op_decl_set_hdf5_infer_size(layers[i].c_str(), op_name, "edge-->node");
                #ifdef SLOPE
                sprintf(sl_name, "sl_edges_L%d", i);    
                sl_edges[i] = set(sl_name, op_edges[i]->size);
                #endif
            }

            if (conf.legacy_mode) {
                sprintf(op_name, "op_bnd_nodes_L%d", i);
                op_bnd_nodes[i] = op_decl_set_hdf5_infer_size(layers[i].c_str(), op_name, "bnd_node-->node.renumbered");
            } else {
                sprintf(op_name, "op_bnd_nodes_L%d", i);
                op_bnd_nodes[i] = op_decl_set_hdf5_infer_size(layers[i].c_str(), op_name, "bnd_node-->node");
                #ifdef SLOPE
                sprintf(sl_name, "sl_bnd_nodes_L%d", i);
                sl_bnd_nodes[i] = set(sl_name, op_bnd_nodes[i]->size);
                #endif
            }

            if (conf.legacy_mode) {
                p_edge_to_nodes[i]          = op_decl_map_hdf5(op_edges[i],     op_nodes[i], 2, layers[i].c_str(), "edge-->node.renumbered");
                p_bnd_node_to_node[i]       = op_decl_map_hdf5(op_bnd_nodes[i], op_nodes[i], 1, layers[i].c_str(), "bnd_node-->node.renumbered");
            } else {
                p_edge_to_nodes[i]          = op_decl_map_hdf5(op_edges[i],     op_nodes[i], 2, layers[i].c_str(), "edge-->node");
                p_bnd_node_to_node[i]       = op_decl_map_hdf5(op_bnd_nodes[i], op_nodes[i], 1, layers[i].c_str(), "bnd_node-->node");

                #ifdef SLOPE
                sprintf(sl_name, "sl_edge_to_nodes_L%d", i);
                sl_maps_edge_to_nodes[i] = sl_name;
                sl_edge_to_nodes[i] = map(sl_name, sl_edges[i], sl_nodes[i], p_edge_to_nodes[i]->map, op_edges[i]->size * 2);
                sprintf(sl_name, "sl_bnd_node_to_node_L%d", i);
                sl_maps_bnd_node_to_node[i] = sl_name;
                sl_bnd_node_to_node[i] = map(sl_name, sl_bnd_nodes[i], sl_nodes[i], p_bnd_node_to_node[i]->map, sl_bnd_nodes[i]->size * 1);
                #endif
            }
            p_bnd_node_groups[i]       = op_decl_dat_hdf5(op_bnd_nodes[i], 1, "int", layers[i].c_str(), "bnd_node-->group");

            if (i > 0) {
                sprintf(op_name, "op_node-->mg_node_L%d", i);
                if (conf.legacy_mode) {
                    p_node_to_mg_node[i-1] = op_decl_map_hdf5(op_nodes[i-1], op_nodes[i], 1, layers[i-1].c_str(), "node-->mg_node.renumbered");
                } else {
                    p_node_to_mg_node[i-1] = op_decl_map_hdf5(op_nodes[i-1], op_nodes[i], 1, layers[i-1].c_str(), "node-->mg_node");
                }

                // TODO: Generate the mapping p_edge_to_mg_nodes, where 
                //         p_edge_to_mg_nodes[i][0] == p_node_to_mg_node[p_edge_to_nodes[i][0]]
                //       and
                //         p_edge_to_mg_nodes[i][1] == p_node_to_mg_node[p_edge_to_nodes[i][1]]
                //       It may be necessary to assume that the input mesh is so large that 
                //       it prevents generation of this mapping in a single compute node.
                p_edge_to_mg_nodes[i-1] = NULL;
            }

            sprintf(op_name, "p_volumes_L%d", i);
            if (conf.legacy_mode) {
                p_volumes[i] = op_decl_dat_hdf5(op_nodes[i], 1, "double", layers[i].c_str(), "areas");
                p_volumes[i]->name = copy_str(op_name);
            }

            if (conf.legacy_mode) {
                p_edge_weights[i] = op_decl_dat_hdf5(op_edges[i],         NDIM, "double", layers[i].c_str(), "edge_weights.recalculated");
            } else {
                p_edge_weights[i] = op_decl_dat_hdf5(op_edges[i],         NDIM, "double", layers[i].c_str(), "edge_weights");
            }
            p_bnd_node_weights[i] = op_decl_dat_hdf5(op_bnd_nodes[i], NDIM, "double", layers[i].c_str(), "bnd_node_weights");

            if (conf.legacy_mode) {
                p_node_coords[i] = op_decl_dat_hdf5(op_nodes[i], NDIM, "double", layers[i].c_str(), "node_coordinates.renumbered");
            } else {
                p_node_coords[i] = op_decl_dat_hdf5(op_nodes[i], NDIM, "double", layers[i].c_str(), "node_coordinates");
            }

            if (conf.validate_result) {
                std::string variables_solution_filepath(conf.input_file_directory);
                if (variables_solution_filepath.size() > 0) {
                    variables_solution_filepath += "/";
                }
                variables_solution_filepath += "solution.variables.L" + number_to_string(i);
                variables_solution_filepath += ".cycles=" + number_to_string(conf.num_cycles);
                variables_solution_filepath += ".h5";

                // op_printf("Checking access of file %s ...\n", variables_solution_filepath.c_str());
                if (access(variables_solution_filepath.c_str(), R_OK) != -1) {
                    std::string dataset_name("p_variables_result_L");
                    dataset_name += number_to_string(i);
                    variables_correct[i] = op_decl_dat_hdf5(op_nodes[i], NVAR, "double", variables_solution_filepath.c_str(), dataset_name.c_str());
                }
                else {
                    op_printf("Cannot find level %d solution file: %s\n", i, variables_solution_filepath.c_str());
                    variables_correct[i] = NULL;
                }
            } else {
                variables_correct[i] = NULL;
            }

            #ifdef SLOPE
            // descriptors
            desc_list flux_desc ({desc(sl_edge_to_nodes[i], READ),
                                    desc(DIRECT, READ),
                                    desc(sl_edge_to_nodes[i], INC)});
            compute_flux_desc[i] = flux_desc;

            desc_list bflux_desc ({desc(DIRECT, READ),
                                    desc(sl_bnd_node_to_node[i], READ),
                                    desc(sl_bnd_node_to_node[i], INC)});
            compute_bflux_desc[i] = bflux_desc;

            desc_list time_desc ({desc(DIRECT, READ),
                                    desc(DIRECT, INC),
                                    desc(DIRECT, WRITE)});
            time_step_desc[i] = time_desc;

            desc_list indirect_rw_descriptor ({desc(sl_edge_to_nodes[i], READ),
                                    desc(DIRECT, READ),
                                    desc(sl_edge_to_nodes[i], INC)});
            indirect_rw_desc[i] = indirect_rw_descriptor;

            desc_list zero_5d_desc ({desc(DIRECT, WRITE)});
            zero_5d_array_desc[i] = zero_5d_desc;



            map_list m ({sl_edge_to_nodes[i]});
            mesh_maps[i] = m;

            insp[i] = insp_init(avg_tile_size, OMP, COL_DEFAULT, &mesh_maps[i]);

            sprintf(sl_name, "compute_flux_L%d", i);
            insp_add_parloop (insp[i], sl_name, sl_edges[i], &compute_flux_desc[i]);

            sprintf(sl_name, "compute_bflux_L%d", i);
            insp_add_parloop (insp[i], sl_name, sl_bnd_nodes[i], &compute_bflux_desc[i]);

            sprintf(sl_name, "time_step_L%d", i);
            insp_add_parloop (insp[i], sl_name, sl_nodes[i],  &time_step_desc[i]);

            sprintf(sl_name, "indirect_rw_L%d", i);
            insp_add_parloop(insp[i], sl_name, sl_edges[i], &indirect_rw_desc[i]);

            sprintf(sl_name, "zero_5d_L%d", i);
            insp_add_parloop(insp[i], sl_name, sl_nodes[i], &zero_5d_array_desc[i]);

            seed_loop = 0;
            insp_run (insp[i], seed_loop);
            insp_print (insp[i], LOW);

            coordinates = (double*) malloc(NDIM * (op_nodes[i]->size) * sizeof(double));
            int size = 3 * sizeof(double);
            for (int n = 0; n < op_nodes[i]->size; n++) {
                coordinates[3*n] = *(double*)(p_node_coords[i]->data + size * n);
                coordinates[3*n+1] = *(double*)(p_node_coords[i]->data + size * n + sizeof(double));
                coordinates[3*n+2] = *(double*)(p_node_coords[i]->data + size * n + (2 * sizeof(double)));
            }
            generate_vtk (insp[i], LOW, sl_nodes[i], coordinates, DIM3);
            free(coordinates);

            exec[i] = exec_init (insp[i]);
            #endif
        }

        

        op_printf("-----------------------------------------------------\n");
        op_printf("Partitioning ...\n");
        if (conf.partitioner == Partitioners::Parmetis) {
            if (conf.partitioner_method == PartitionerMethods::Geom) {
                op_partition("PARMETIS", "GEOM", op_nodes[0], OP_ID, p_node_coords[0]);
            }
            else if (conf.partitioner_method == PartitionerMethods::KWay) {
                op_partition("PARMETIS", "KWAY", op_nodes[0], p_edge_to_nodes[0], p_node_coords[0]);
            }
            else if (conf.partitioner_method == PartitionerMethods::GeomKWay) {
                op_partition("PARMETIS", "GEOMKWAY", op_nodes[0], p_edge_to_nodes[0], p_node_coords[0]);
            }
        }
        else if (conf.partitioner == Partitioners::Ptscotch) {
            if (conf.partitioner_method == PartitionerMethods::Geom) {
                op_partition("PTSCOTCH", "GEOM", op_nodes[0], OP_ID, p_node_coords[0]);
            }
            else if (conf.partitioner_method == PartitionerMethods::KWay) {
                op_partition("PTSCOTCH", "KWAY", op_nodes[0], p_edge_to_nodes[0], p_node_coords[0]);
            }
            else if (conf.partitioner_method == PartitionerMethods::GeomKWay) {
                op_partition("PTSCOTCH", "GEOMKWAY", op_nodes[0], p_edge_to_nodes[0], p_node_coords[0]);
            }
        }
        else if (conf.partitioner == Partitioners::Inertial) {
            op_partition("INERTIAL", "", op_nodes[0], OP_ID, p_node_coords[0]);
        }
        op_printf("PARTITIONING COMPLETE\n");
        op_renumber(p_edge_to_nodes[0]);

        for (int i=0; i<levels; i++) {
            sprintf(op_name, "p_variables_L%d", i);
            p_variables[i] = op_decl_dat_temp_char(op_nodes[i], NVAR, "double", sizeof(double), op_name);
            sprintf(op_name, "p_old_variables_L%d", i);
            p_old_variables[i] = op_decl_dat_temp_char(op_nodes[i], NVAR, "double", sizeof(double), op_name);
            sprintf(op_name, "p_residuals_L%d", i);
            p_residuals[i] = op_decl_dat_temp_char(op_nodes[i], NVAR, "double", sizeof(double), op_name);

            if (!conf.legacy_mode) {
                // Need to calculate cell volumes:
                sprintf(op_name, "p_volumes_L%d", i);
                p_volumes[i] = op_decl_dat_temp_char(op_nodes[i], 1, "double", sizeof(double), op_name);
            }

            sprintf(op_name, "p_step_factors_L%d", i);
            p_step_factors[i] = op_decl_dat_temp_char(op_nodes[i], 1, "double", sizeof(double), op_name);

            sprintf(op_name, "p_fluxes_L%d", i);
            p_fluxes[i] = op_decl_dat_temp_char(op_nodes[i], NVAR, "double", sizeof(double), op_name);

            if (i > 0) {
                sprintf(op_name, "p_up_scratch_L%d", i);
                p_up_scratch[i] = op_decl_dat_temp_char(op_nodes[i], 1, "int", sizeof(double), op_name);
            } else {
                p_up_scratch[i] = NULL;
            }
        }
    }

    // Initialise variables:
    for (int i=0; i<levels; i++) {
        op_par_loop_initialize_variables_kernel("initialize_variables_kernel",op_nodes[i],
                    op_arg_dat(p_variables[i],-1,OP_ID,5,"double",OP_WRITE));
        op_par_loop_zero_5d_array_kernel("zero_5d_array_kernel",op_nodes[i],
                    op_arg_dat(p_fluxes[i],-1,OP_ID,5,"double",OP_WRITE));

        if (!conf.legacy_mode) {
            op_par_loop_zero_1d_array_kernel("zero_1d_array_kernel",op_nodes[i],
                        op_arg_dat(p_volumes[i],-1,OP_ID,1,"double",OP_WRITE));
            op_par_loop_calculate_cell_volumes("calculate_cell_volumes",op_edges[i],
                        op_arg_dat(p_node_coords[i],0,p_edge_to_nodes[i],3,"double",OP_READ),
                        op_arg_dat(p_node_coords[i],1,p_edge_to_nodes[i],3,"double",OP_READ),
                        op_arg_dat(p_edge_weights[i],-1,OP_ID,3,"double",OP_INC),
                        op_arg_dat(p_volumes[i],0,p_edge_to_nodes[i],1,"double",OP_INC),
                        op_arg_dat(p_volumes[i],1,p_edge_to_nodes[i],1,"double",OP_INC));
        }
    }

    // Fudge the weights to delay occurrence of negative densities in HDF5 meshes:
    for (int l=0; l<levels; l++) {
        op_par_loop_dampen_ewt("dampen_ewt",op_edges[l],
                    op_arg_dat(p_edge_weights[l],-1,OP_ID,3,"double",OP_INC));
        op_par_loop_dampen_ewt("dampen_ewt",op_bnd_nodes[l],
                    op_arg_dat(p_bnd_node_weights[l],-1,OP_ID,3,"double",OP_INC));
    }

    op_printf("-----------------------------------------------------\n");
    op_printf("Compute beginning\n");

    op_timers(&cpu_t1, &wall_t1);

    int level = 0;
    int mg_dir = MG_UP;
    int i = 0;
    double rms = 0.0;
    int bad_val_count = 0;
    double min_dt = std::numeric_limits<double>::max();
    double flux_cpu_t1, flux_cpu_t2, flux_wall_t1, flux_wall_t2, flux_time=0.0;
    while(i < conf.num_cycles)
    {
        #ifdef LOG_PROGRESS
            op_printf("Performing MG cycle %d / %d", i+1, conf.num_cycles);
        #else
            if (level==0)
            op_printf("Performing MG cycle %d / %d", i+1, conf.num_cycles);
        #endif

        op_par_loop_copy_double_kernel("copy_double_kernel",op_nodes[level],
                    op_arg_dat(p_variables[level],-1,OP_ID,5,"double",OP_READ),
                    op_arg_dat(p_old_variables[level],-1,OP_ID,5,"double",OP_WRITE));

        // for the first iteration we compute the time step
        op_par_loop_calculate_dt_kernel("calculate_dt_kernel",op_nodes[level],
                    op_arg_dat(p_variables[level],-1,OP_ID,5,"double",OP_READ),
                    op_arg_dat(p_volumes[level],-1,OP_ID,1,"double",OP_READ),
                    op_arg_dat(p_step_factors[level],-1,OP_ID,1,"double",OP_WRITE));
        min_dt = std::numeric_limits<double>::max();
        op_par_loop_get_min_dt_kernel("get_min_dt_kernel",op_nodes[level],
                    op_arg_dat(p_step_factors[level],-1,OP_ID,1,"double",OP_READ),
                    op_arg_gbl(&min_dt,1,"double",OP_MIN));
        if (min_dt < 0.0f) {
          op_printf("Fatal error during 'step factor' calculation, min_dt = %.5e\n", min_dt);
          op_exit();
          return 1;
        }
        op_par_loop_compute_step_factor_kernel("compute_step_factor_kernel",op_nodes[level],
                    op_arg_dat(p_variables[level],-1,OP_ID,5,"double",OP_READ),
                    op_arg_dat(p_volumes[level],-1,OP_ID,1,"double",OP_READ),
                    op_arg_gbl(&min_dt,1,"double",OP_READ),
                    op_arg_dat(p_step_factors[level],-1,OP_ID,1,"double",OP_WRITE));
        #ifdef SLOPE
        int ncolors = exec_num_colors (exec[level]);
        #endif
        int rkCycle;
        for (rkCycle=0; rkCycle<RK; rkCycle++)
        {
            #ifdef LOG_PROGRESS
                op_printf(" RK cycle %d / %d\n", rkCycle+1, RK);
            #endif

            #ifdef SLOPE
            //for each colour
            for (int color = 0; color < ncolors; color++) {
            // for all tiles of this color
                const int n_tiles_per_color = exec_tiles_per_color (exec[level], color);

                #pragma omp parallel for
                for (int j = 0; j < n_tiles_per_color; j++) {
                    // execute the tile
                    tile_t* tile = exec_tile_at (exec[level], color, j);
                    int loop_size;

                    // loop compute_flux_edge
                    iterations_list& le2n_0 = tile_get_local_map (tile, 0, sl_maps_edge_to_nodes[level]);
                    iterations_list& iterations_0 = tile_get_iterations (tile, 0);
                    loop_size = tile_loop_size (tile, 0);

                    op_timers_core(&flux_cpu_t1, &flux_wall_t1);

                    const double* p_variables_data = (double*)(p_variables[level]->data);
                    const double* p_edge_weights_data = (double*)(p_edge_weights[level]->data);
                    double* p_fluxes_data    = (double*)(p_fluxes[level]->data);

                    #ifndef VECTORIZE
                      for (int k = 0; k < loop_size; k++) {
                          compute_flux_edge_kernel(
                              &p_variables_data[le2n_0[k*2 + 0] * 5],
                              &p_variables_data[le2n_0[k*2 + 1] * 5],
                              &p_edge_weights_data[iterations_0[k] * 3],
                              &p_fluxes_data[le2n_0[k*2 + 0] * 5],
                              &p_fluxes_data[le2n_0[k*2 + 1] * 5]);
                      }
                    #else
                      int simd_end = (loop_size/SIMD_BLOCK_SIZE)*SIMD_BLOCK_SIZE;

                      ALIGNED_double double dat0[5][SIMD_BLOCK_SIZE];
                      ALIGNED_double double dat1[5][SIMD_BLOCK_SIZE];
                      ALIGNED_double double dat3[5][SIMD_BLOCK_SIZE];
                      ALIGNED_double double dat4[5][SIMD_BLOCK_SIZE];

                      for (int n=0 ; n < simd_end; n+=SIMD_BLOCK_SIZE) {
                          // "sl" is SIMD lane:
                          for (int sl=0; sl<SIMD_BLOCK_SIZE; sl++ ){
                            int k = n+sl;
                            int idx0 = le2n_0[k*2 + 0];
                            int idx1 = le2n_0[k*2 + 1];

                            for (int v=0; v<5; v++) {
                                dat0[v][sl] = p_variables_data[idx0*5 + v];
                                dat1[v][sl] = p_variables_data[idx1*5 + v];
                                dat3[v][sl] = 0.0;
                                dat4[v][sl] = 0.0;
                            }
                          }

                          #pragma omp simd simdlen(SIMD_VEC)
                          for (int sl=0; sl<SIMD_BLOCK_SIZE; sl++ ){
                            int k = n+sl;
                            int ewt_idx = iterations_0[k];
                            compute_flux_edge_kernel_vec(
                              dat0,
                              dat1,
                              &p_edge_weights_data[ewt_idx*3],
                              dat3,
                              dat4,
                              sl);
                          }

                          for ( int sl=0; sl<SIMD_BLOCK_SIZE; sl++ ){
                            int k = n+sl;
                            int idx3 = le2n_0[k*2 + 0];
                            int idx4 = le2n_0[k*2 + 1];

                            for (int v=0; v<5; v++) {
                                p_fluxes_data[idx3*5 + v] += dat3[v][sl];
                                p_fluxes_data[idx4*5 + v] += dat4[v][sl];
                            }
                          }
                      }

                      // remainder:
                      for (int n = simd_end ; n < loop_size; n++) {
                          int k = n;
                          compute_flux_edge_kernel(
                              &p_variables_data[le2n_0[k*2 + 0] * 5],
                              &p_variables_data[le2n_0[k*2 + 1] * 5],
                              &p_edge_weights_data[iterations_0[k] * 3],
                              &p_fluxes_data[le2n_0[k*2 + 0] * 5],
                              &p_fluxes_data[le2n_0[k*2 + 1] * 5]);
                      }
                    #endif

                    op_timers_core(&flux_cpu_t2, &flux_wall_t2);
                    flux_time += flux_wall_t2 - flux_wall_t1;

                    // loop compute_bnd_node_flux
                    iterations_list& lbe2n_1 = tile_get_local_map (tile, 1, sl_maps_bnd_node_to_node[level]);
                    iterations_list& iterations_1 = tile_get_iterations (tile, 1);
                    loop_size = tile_loop_size (tile, 1);
                  
                    for (int k = 0; k < loop_size; k++) {
                        compute_bnd_node_flux_kernel(
                             (int*)(p_bnd_node_groups[level]->data + ((iterations_1[k] * 1) * sizeof(int))),
                             (double*)(p_bnd_node_weights[level]->data + ((iterations_1[k] * 3) * sizeof(double))),
                             (double*)(p_variables[level]->data + ((lbe2n_1[k + 0] * 5) * sizeof(double))),
                             (double*)(p_fluxes[level]->data + ((lbe2n_1[k + 0] * 5) * sizeof(double))));
                    }

                    // loop time_step
                    iterations_list& iterations_2 = tile_get_iterations (tile, 2);
                    loop_size = tile_loop_size (tile, 2);
                    
                    for (int k = 0; k < loop_size; k++) {
                        time_step_kernel(
                            &rkCycle,
                            (double*)(p_step_factors[level]->data + ((iterations_2[k] * 1) * sizeof(double))),
                            (double*)(p_fluxes[level]->data + ((iterations_2[k] * 5) * sizeof(double))),
                            (double*)(p_old_variables[level]->data + ((iterations_2[k] * 5) * sizeof(double))),
                            (double*)(p_variables[level]->data + ((iterations_2[k] * 5) * sizeof(double))));
                    }

                      // loop indirect_rw
                    iterations_list& le2n_3 = tile_get_local_map (tile, 3, sl_maps_edge_to_nodes[level]);
                    iterations_list& iterations_3 = tile_get_iterations (tile, 3);
                    loop_size = tile_loop_size (tile, 3);

                    for (int k = 0; k < loop_size; k++) {
                        indirect_rw_kernel(
                            (double*)(p_variables[level]->data + ((le2n_3[2 * k + 0] * 5) * sizeof(double))),
                            (double*)(p_variables[level]->data + ((le2n_3[2 * k + 1] * 5) * sizeof(double))),
                            (double*)(p_edge_weights[level]->data + ((iterations_3[k] * 3) * sizeof(double))),
                            (double*)(p_fluxes[level]->data + ((le2n_3[2 * k + 0] * 5) * sizeof(double))),
                            (double*)(p_fluxes[level]->data + ((le2n_3[2 * k + 1] * 5) * sizeof(double))));
                    }

                     // loop zero_5d_array
                    iterations_list& iterations_4 = tile_get_iterations (tile, 4);
                    loop_size = tile_loop_size (tile, 4);
                    #pragma omp simd
                    for (int k = 0; k < loop_size; k++) {
                        zero_5d_array_kernel(
                            (double*)(p_fluxes[level]->data + ((iterations_4[k] * 5) * sizeof(double))));
                    }
                }
                
            }
	
            #else

            op_par_loop_compute_flux_edge_kernel_instrumented("compute_flux_edge_kernel",op_edges[level],
                        op_arg_dat(p_variables[level],0,p_edge_to_nodes[level],5,"double",OP_READ),
                        op_arg_dat(p_variables[level],1,p_edge_to_nodes[level],5,"double",OP_READ),
                        op_arg_dat(p_edge_weights[level],-1,OP_ID,3,"double",OP_READ),
                        op_arg_dat(p_fluxes[level],0,p_edge_to_nodes[level],5,"double",OP_INC),
                        op_arg_dat(p_fluxes[level],1,p_edge_to_nodes[level],5,"double",OP_INC)
                        #ifdef VERIFY_OP2_TIMING
                          , &flux_kernel_compute_times[level], &flux_kernel_sync_times[level]
                        #endif
                        , &flux_kernel_iter_counts[level]
                        #ifdef PAPI
                        , &flux_kernel_event_counts[level*num_events], event_set, num_events
                        #endif
                        );

            op_par_loop_compute_bnd_node_flux_kernel("compute_bnd_node_flux_kernel",op_bnd_nodes[level],
                        op_arg_dat(p_bnd_node_groups[level],-1,OP_ID,1,"int",OP_READ),
                        op_arg_dat(p_bnd_node_weights[level],-1,OP_ID,3,"double",OP_READ),
                        op_arg_dat(p_variables[level],0,p_bnd_node_to_node[level],5,"double",OP_READ),
                        op_arg_dat(p_fluxes[level],0,p_bnd_node_to_node[level],5,"double",OP_INC));

            op_par_loop_time_step_kernel("time_step_kernel",op_nodes[level],
                        op_arg_gbl(&rkCycle,1,"int",OP_READ),
                        op_arg_dat(p_step_factors[level],-1,OP_ID,1,"double",OP_READ),
                        op_arg_dat(p_fluxes[level],-1,OP_ID,5,"double",OP_INC),
                        op_arg_dat(p_old_variables[level],-1,OP_ID,5,"double",OP_READ),
                        op_arg_dat(p_variables[level],-1,OP_ID,5,"double",OP_WRITE));

            op_par_loop_indirect_rw_kernel("indirect_rw_kernel",op_edges[level],
                        op_arg_dat(p_variables[level],0,p_edge_to_nodes[level],5,"double",OP_READ),
                        op_arg_dat(p_variables[level],1,p_edge_to_nodes[level],5,"double",OP_READ),
                        op_arg_dat(p_edge_weights[level],-1,OP_ID,3,"double",OP_READ),
                        op_arg_dat(p_fluxes[level],0,p_edge_to_nodes[level],5,"double",OP_INC),
                        op_arg_dat(p_fluxes[level],1,p_edge_to_nodes[level],5,"double",OP_INC));
            op_par_loop_zero_5d_array_kernel("zero_5d_array_kernel",op_nodes[level],
                        op_arg_dat(p_fluxes[level],-1,OP_ID,5,"double",OP_WRITE));

            #endif
        }

        op_par_loop_residual_kernel("residual_kernel",op_nodes[level],
                    op_arg_dat(p_old_variables[level],-1,OP_ID,5,"double",OP_READ),
                    op_arg_dat(p_variables[level],-1,OP_ID,5,"double",OP_READ),
                    op_arg_dat(p_residuals[level],-1,OP_ID,5,"double",OP_WRITE));
        if (level == 0) {
            rms = 0.0;
            op_par_loop_calc_rms_kernel("calc_rms_kernel",op_nodes[level],
                        op_arg_dat(p_residuals[level],-1,OP_ID,5,"double",OP_READ),
                        op_arg_gbl(&rms,1,"double",OP_INC));
            rms = sqrt(rms / double(op_get_size(op_nodes[level])));
            // op_printf(" (RMS = %.3e)", rms);
            // Until I get the HDF5 meshes working correctly, no point displaying incorrect RMS.

            #ifdef OPENACC
              // count_bad_vals() invokes isnan(), unsupported with OpenACC.
            #else
                op_par_loop_count_bad_vals("count_bad_vals",op_nodes[level],
                            op_arg_dat(p_variables[level],-1,OP_ID,5,"double",OP_READ),
                            op_arg_gbl(&bad_val_count,1,"int",OP_INC));
            #endif
            if (bad_val_count > 0) {
                op_printf("Bad variable values detected, aborting\n");
                op_exit();
                return 1;
            }
            op_printf("\n");
        }

        if (levels <= 1) {
            i++;
        }
        else {
            if(mg_dir == MG_UP)
            {
                level++;

                op_par_loop_up_pre_kernel("up_pre_kernel",op_nodes[level-1],
                            op_arg_dat(p_variables[level],0,p_node_to_mg_node[level-1],5,"double",OP_WRITE),
                            op_arg_dat(p_up_scratch[level],0,p_node_to_mg_node[level-1],1,"int",OP_WRITE));

                op_par_loop_up_kernel("up_kernel",op_nodes[level-1],
                            op_arg_dat(p_variables[level-1],-1,OP_ID,5,"double",OP_READ),
                            op_arg_dat(p_variables[level],0,p_node_to_mg_node[level-1],5,"double",OP_INC),
                            op_arg_dat(p_up_scratch[level],0,p_node_to_mg_node[level-1],1,"int",OP_INC));

                op_par_loop_up_post_kernel("up_post_kernel",op_nodes[level],
                            op_arg_dat(p_variables[level],-1,OP_ID,5,"double",OP_INC),
                            op_arg_dat(p_up_scratch[level],-1,OP_ID,1,"int",OP_READ));

                if(level == levels-1)
                {
                    mg_dir = MG_DOWN;
                }
            }
            else
            {
                level--;

                if (p_edge_to_mg_nodes[level] != NULL) {
                    // NOTE: Because I have not yet generated the mapping 'p_edge_to_mg_nodes', I have not 
                    // tested these 'down_v2_kernel' loops at all. I have simply ported it from MG-CFD-app-plain
                    op_par_loop_down_v2_kernel_pre("down_v2_kernel_pre",op_nodes[level],
                                op_arg_dat(p_residuals_prolonged[level],-1,OP_ID,5,"double",OP_WRITE),
                                op_arg_dat(p_residuals_prolonged_wsum[level],-1,OP_ID,1,"double",OP_WRITE));
                    op_par_loop_down_v2_kernel("down_v2_kernel",op_edges[level],
                                op_arg_dat(p_node_coords[level],0,p_edge_to_nodes[level],3,"double",OP_READ),
                                op_arg_dat(p_node_coords[level],1,p_edge_to_nodes[level],3,"double",OP_READ),
                                op_arg_dat(p_node_coords[level+1],0,p_edge_to_mg_nodes[level],3,"double",OP_READ),
                                op_arg_dat(p_node_coords[level+1],1,p_edge_to_mg_nodes[level],3,"double",OP_READ),
                                op_arg_dat(p_residuals[level+1],0,p_edge_to_mg_nodes[level],5,"double",OP_READ),
                                op_arg_dat(p_residuals[level+1],1,p_edge_to_mg_nodes[level],5,"double",OP_READ),
                                op_arg_dat(p_residuals_prolonged[level],0,p_edge_to_nodes[level],5,"double",OP_INC),
                                op_arg_dat(p_residuals_prolonged[level],1,p_edge_to_nodes[level],5,"double",OP_INC),
                                op_arg_dat(p_residuals_prolonged_wsum[level],0,p_edge_to_nodes[level],1,"double",OP_INC),
                                op_arg_dat(p_residuals_prolonged_wsum[level],1,p_edge_to_nodes[level],1,"double",OP_INC));
                    op_par_loop_down_v2_kernel_post("down_v2_kernel_post",op_nodes[level],
                                op_arg_dat(p_residuals_prolonged[level],-1,OP_ID,5,"double",OP_READ),
                                op_arg_dat(p_residuals_prolonged_wsum[level],-1,OP_ID,1,"double",OP_READ),
                                op_arg_dat(p_residuals[level],-1,OP_ID,5,"double",OP_READ),
                                op_arg_dat(p_variables[level],-1,OP_ID,5,"double",OP_INC));
                } else {
                    op_par_loop_down_kernel("down_kernel",op_nodes[level],
                                op_arg_dat(p_variables[level],-1,OP_ID,5,"double",OP_INC),
                                op_arg_dat(p_residuals[level],-1,OP_ID,5,"double",OP_READ),
                                op_arg_dat(p_node_coords[level],-1,OP_ID,3,"double",OP_READ),
                                op_arg_dat(p_residuals[level+1],0,p_node_to_mg_node[level],5,"double",OP_READ),
                                op_arg_dat(p_node_coords[level+1],0,p_node_to_mg_node[level],3,"double",OP_READ));
                }

                if(level == 0)
                {
                    mg_dir = MG_UP;
                    i++;
                }
            }
        }
    }
    op_printf("\n");
	op_printf("Compute complete\n");

    op_timers(&cpu_t2, &wall_t2);
    op_printf("Max total runtime = %f\n", wall_t2 - wall_t1);
    op_printf("- flux compute = %f\n", flux_time);

    // Write summary performance data to stdout:
    op_timing_output();

    // Write full performance data to file:
    std::string csv_out_filepath(conf.output_file_prefix);
    csv_out_filepath += "op2_performance_data.csv";
    op_printf("Writing OP2 timings to file: %s\n", csv_out_filepath.c_str());
    op_timings_to_csv(csv_out_filepath.c_str());

    if (conf.validate_result) {
        op_printf("-----------------------------------------------------\n");

        bool value_check_failed = false;
        op_printf("Looking for NaN and infinity values ...");
        for (int l=0; l<levels; l++) {
            int bad_val_count = 0;
            op_par_loop_count_bad_vals("count_bad_vals",op_nodes[l],
                        op_arg_dat(p_variables[l],-1,OP_ID,5,"double",OP_READ),
                        op_arg_gbl(&bad_val_count,1,"int",OP_INC));
            if (bad_val_count > 0) {
                value_check_failed = true;
                op_printf("\n");
                op_printf("Value check of MG level %d failed: %d bad values detected\n", l, bad_val_count);
                break;
            }
        }
        if (!value_check_failed) {
            op_printf(" None found\n");
            bool validation_failed = false;
            op_printf("Validating result against solution ...");
            for (int l=0; l<levels; l++) {
                if (variables_correct[l] == NULL) {
                    op_printf("\n");
                    op_printf("- Do not have solution for level %d, cannot validate\n", l);
                    validation_failed = true;
                    continue;
                }

                sprintf(op_name, "p_var_diff_L%d", l);
                op_dat variables_difference = op_decl_dat_temp_char(op_nodes[l], NVAR, "double", sizeof(double), op_name);

                op_par_loop_identify_differences("identify_differences",op_nodes[l],
                            op_arg_dat(p_variables[l],-1,OP_ID,5,"double",OP_READ),
                            op_arg_dat(variables_correct[l],-1,OP_ID,5,"double",OP_READ),
                            op_arg_dat(variables_difference,-1,OP_ID,5,"double",OP_WRITE));

                int count = 0;
                op_par_loop_count_non_zeros("count_non_zeros",op_nodes[l],
                            op_arg_dat(variables_difference,-1,OP_ID,5,"double",OP_READ),
                            op_arg_gbl(&count,1,"int",OP_INC));
                if (count > 0) {
                    validation_failed = true;
                    op_printf("\n");
                    op_printf("Validation of MG level %d failed: %d incorrect values in 'variables' array\n", l, count);
                    break;
                } else {
                    // op_printf("Validation of MG level %d successful\n", l);
                }
            }

            if (validation_failed) {
                op_printf("Validation failed\n");
            } else {
                op_printf(" Result correct\n");
                op_printf("Validation passed\n");
            }
        }
    }

    if (conf.output_anything) {
        op_printf("-----------------------------------------------------\n");
        op_printf("Writing out data...\n");
        char* h5_out_name = alloc<char>(100);
        std::string prefix(conf.output_file_prefix);
        for (int l=0; l<levels; l++)
        {
            std::string suffix = std::string(".L") + number_to_string(l) 
                               + "." + "cycles=" + number_to_string(conf.num_cycles);

            int number_of_edges = op_get_size(op_edges[l]);
            int nel     = op_get_size(op_nodes[l]);

            // Dump volumes:
            if (conf.output_volumes) {
                const char* old_name = p_volumes[l]->name;
                sprintf(op_name, "p_volumes_result_L%d", l);
                p_volumes[l]->name = strdup(op_name);
                sprintf(h5_out_name, "%svolumes%s.h5", prefix.c_str(), suffix.c_str());
                op_fetch_data_hdf5_file(p_volumes[l], h5_out_name);
                p_volumes[l]->name = old_name;
            }

            // Dump step factors:
            if (conf.output_step_factors) {
                const char* old_name = p_step_factors[l]->name;
                sprintf(op_name, "p_step_factors_result_L%d", l);
                p_step_factors[l]->name = strdup(op_name);
                sprintf(h5_out_name, "%sstep_factors%s.h5", prefix.c_str(), suffix.c_str());
                op_fetch_data_hdf5_file(p_step_factors[l], h5_out_name);
                p_step_factors[l]->name = old_name;
            }

            // Dump fluxes:
            if (conf.output_fluxes) {
                const char* old_name = p_fluxes[l]->name;
                sprintf(op_name, "p_fluxes_result_L%d", l);
                p_fluxes[l]->name = strdup(op_name);
                sprintf(h5_out_name, "%sfluxes%s.h5", prefix.c_str(), suffix.c_str());
                op_fetch_data_hdf5_file(p_fluxes[l], h5_out_name);
                p_fluxes[l]->name = old_name;
            }
            
            // Dump variables:
            if (conf.output_variables) {
                const char* old_name = p_variables[l]->name;
                sprintf(op_name, "p_variables_result_L%d", l);
                p_variables[l]->name = strdup(op_name);
                sprintf(h5_out_name, "%svariables%s.h5", prefix.c_str(), suffix.c_str());
                op_fetch_data_hdf5_file(p_variables[l], h5_out_name);
                p_variables[l]->name = old_name;
            }
        }
    }

    int my_rank=0;
    #ifdef MPI_ON
    op_rank(&my_rank);
    #endif
    #ifdef PAPI
        dump_papi_counters_to_file(
            my_rank, 
            levels, 
            num_events, 
            events, 
            flux_kernel_event_counts, 
            conf.output_file_prefix);
    #endif

    #ifdef DUMP_EXT_PERF_DATA
        dump_perf_data_to_file(
            my_rank, 
            levels, 
            #ifdef VERIFY_OP2_TIMING
                flux_kernel_compute_times, 
                flux_kernel_sync_times,
            #endif
            flux_kernel_iter_counts, 
            conf.output_file_prefix);
    #endif

    op_printf("-----------------------------------------------------\n");
    op_printf("Winding down OP2\n");
    op_exit();

    return 0;
}
