//
// auto-generated by op2.py
//

// header
#include "op_lib_cpp.h"

// user kernel files
#include "initialize_variables_kernel_omp4kernel.cpp"
#include "zero_5d_array_kernel_omp4kernel.cpp"
#include "zero_1d_array_kernel_omp4kernel.cpp"
#include "calculate_cell_volumes_omp4kernel.cpp"
#include "dampen_ewt_omp4kernel.cpp"
#include "copy_double_kernel_omp4kernel.cpp"
#include "calculate_dt_kernel_omp4kernel.cpp"
#include "get_min_dt_kernel_omp4kernel.cpp"
#include "compute_step_factor_kernel_omp4kernel.cpp"
#include "compute_flux_edge_kernel_omp4kernel.cpp"
#include "compute_bnd_node_flux_kernel_omp4kernel.cpp"
#include "time_step_kernel_omp4kernel.cpp"
#include "indirect_rw_kernel_omp4kernel.cpp"
#include "residual_kernel_omp4kernel.cpp"
#include "calc_rms_kernel_omp4kernel.cpp"
#include "count_bad_vals_omp4kernel.cpp"
#include "up_pre_kernel_omp4kernel.cpp"
#include "up_kernel_omp4kernel.cpp"
#include "up_post_kernel_omp4kernel.cpp"
#include "down_v2_kernel_pre_omp4kernel.cpp"
#include "down_v2_kernel_omp4kernel.cpp"
#include "down_v2_kernel_post_omp4kernel.cpp"
#include "down_kernel_omp4kernel.cpp"
#include "identify_differences_omp4kernel.cpp"
#include "count_non_zeros_omp4kernel.cpp"
