//
// auto-generated by op2.py
//

#ifdef _OPENMP
  #include <omp.h>
#endif

// global constants

// header
#include "op_lib_cpp.h"

// user kernel files
#include "initialize_variables_kernel_kernel.cpp"
#include "zero_5d_array_kernel_kernel.cpp"
#include "zero_1d_array_kernel_kernel.cpp"
#include "calculate_cell_volumes_kernel.cpp"
#include "dampen_ewt_kernel.cpp"
#include "copy_double_kernel_kernel.cpp"
#include "calculate_dt_kernel_kernel.cpp"
#include "get_min_dt_kernel_kernel.cpp"
#include "compute_step_factor_kernel_kernel.cpp"
#include "compute_flux_edge_kernel_kernel.cpp"
#include "compute_bnd_node_flux_kernel_kernel.cpp"
#include "time_step_kernel_kernel.cpp"
#include "indirect_rw_kernel_kernel.cpp"
#include "residual_kernel_kernel.cpp"
#include "calc_rms_kernel_kernel.cpp"
#include "count_bad_vals_kernel.cpp"
#include "up_pre_kernel_kernel.cpp"
#include "up_kernel_kernel.cpp"
#include "up_post_kernel_kernel.cpp"
#include "down_v2_kernel_pre_kernel.cpp"
#include "down_v2_kernel_kernel.cpp"
#include "down_v2_kernel_post_kernel.cpp"
#include "down_kernel_kernel.cpp"
#include "identify_differences_kernel.cpp"
#include "count_non_zeros_kernel.cpp"
