include $(OP2_INSTALL_PATH)/../makefiles/common.mk

APP_NAME := euler3d
APP_SRC := euler3d.cpp

OP2_LIBS_WITH_HDF5 := true

include $(OP2_INSTALL_PATH)/../makefiles/c_app.mk

.PHONY: clean_convert_mesh
